#ifndef PLUGIN_HOOKS_H
#define PLUGIN_HOOKS_H

extern "C" {
#include <janus/debug.h>
#include <janus/apierror.h>
#include <janus/config.h>
#include <janus/mutex.h>
#include <janus/rtp.h>
#include <janus/rtcp.h>
#include <janus/record.h>
#include <janus/utils.h>
#include <janus/plugin.h>
}

/* Plugin information */
#define JANUS_ULTRASOUND_VERSION			5
#define JANUS_ULTRASOUND_VERSION_STRING	"0.0.5"
#define JANUS_ULTRASOUND_DESCRIPTION		"This is a ultrasound plugin for Janus, allowing WebRTC peers to watch/listen to pre-recorded files or media generated by gstreamer."
#define JANUS_ULTRASOUND_NAME			"JANUS Streaming plugin"
#define JANUS_ULTRASOUND_AUTHOR			"Meetecho s.r.l."
#define JANUS_ULTRASOUND_PACKAGE			"plugin.ultrasound"

extern "C" {
/* Plugin methods */
janus_plugin *create(void);
int janus_ultrasound_init(janus_callbacks *callback, const char *config_path);
void janus_ultrasound_destroy(void);
int janus_ultrasound_get_api_compatibility(void);
int janus_ultrasound_get_version(void);
const char *janus_ultrasound_get_version_string(void);
const char *janus_ultrasound_get_description(void);
const char *janus_ultrasound_get_name(void);
const char *janus_ultrasound_get_author(void);
const char *janus_ultrasound_get_package(void);
void janus_ultrasound_create_session(janus_plugin_session *handle, int *error);
struct janus_plugin_result *janus_ultrasound_handle_message(janus_plugin_session *handle, char *transaction, char *message, char *sdp_type, char *sdp);
void janus_ultrasound_setup_media(janus_plugin_session *handle);
void janus_ultrasound_incoming_rtp(janus_plugin_session *handle, int video, char *buf, int len);
void janus_ultrasound_incoming_rtcp(janus_plugin_session *handle, int video, char *buf, int len);
void janus_ultrasound_incoming_data(janus_plugin_session *handle, char *buf, int len);
void janus_ultrasound_hangup_media(janus_plugin_session *handle);
void janus_ultrasound_destroy_session(janus_plugin_session *handle, int *error);
char *janus_ultrasound_query_session(janus_plugin_session *handle);
}

/* Plugin setup */
static janus_plugin janus_ultrasound_plugin =
{
        /*.init =*/ janus_ultrasound_init,
        /*.destroy =*/ janus_ultrasound_destroy,

        /*.get_api_compatibility =*/ janus_ultrasound_get_api_compatibility,
        /*.get_version =*/ janus_ultrasound_get_version,
        /*.get_version_string =*/ janus_ultrasound_get_version_string,
        /*.get_description =*/ janus_ultrasound_get_description,
        /*.get_name =*/ janus_ultrasound_get_name,
        /*.get_author =*/ janus_ultrasound_get_author,
        /*.get_package =*/ janus_ultrasound_get_package,

        /*.create_session =*/ janus_ultrasound_create_session,
        /*.handle_message =*/ janus_ultrasound_handle_message,
        /*.setup_media =*/ janus_ultrasound_setup_media,
        /*.incoming_rtp =*/ janus_ultrasound_incoming_rtp,
        /*.incoming_rtcp =*/ janus_ultrasound_incoming_rtcp,

        /*.incoming_data =*/ janus_ultrasound_incoming_data,
        /*.slow_link =*/ NULL,
        /*.hangup_media =*/ janus_ultrasound_hangup_media,
        /*.destroy_session =*/ janus_ultrasound_destroy_session,
        /*.query_session =*/ janus_ultrasound_query_session,
};


#endif
